# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmsCompanies',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('custid', models.CharField(blank=True, max_length=100, null=True)),
                ('clientcode', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('street2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('st', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('ext', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('ext2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone3', models.CharField(blank=True, max_length=100, null=True)),
                ('ext3', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('faxext', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('ftpsite', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email2', models.CharField(blank=True, max_length=100, null=True)),
                ('uspspermit', models.CharField(blank=True, max_length=100, null=True)),
                ('shipacct', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('card_recd', models.CharField(blank=True, max_length=100, null=True)),
                ('curr_dr13', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_rep', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_exempt', models.CharField(blank=True, max_length=100, null=True)),
                ('terms', models.CharField(blank=True, max_length=100, null=True)),
                ('ohdir', models.CharField(blank=True, max_length=100, null=True)),
                ('gmacctno', models.CharField(blank=True, max_length=100, null=True)),
                ('gmcreator', models.CharField(blank=True, max_length=100, null=True)),
                ('gmlastuse', models.CharField(blank=True, max_length=100, null=True)),
                ('cwretail', models.CharField(max_length=100)),
                ('buymas', models.CharField(max_length=100)),
                ('hibernate', models.CharField(max_length=100)),
                ('deadbeat', models.CharField(max_length=100)),
                ('ac_id', models.CharField(max_length=100)),
            ],
        ),
    ]
